services:
  postgres:
    image: postgres:16
    container_name: ats_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ats
      POSTGRES_PASSWORD: ats_password
      POSTGRES_DB: ats_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
